"use client";
import { Check } from "lucide-react";
import type { Report } from "@/lib/types";
import { CategoryBars, Donut, Meter, Sparkline } from "../charts";
import { Card, CardHeader, StatCard } from "../ui/card";
import { MethodBadge, SeverityBadge } from "../ui/badge";
import { Button } from "../ui/button";
import { FailureCard } from "./failures";

const Li = ({ children }: { children: React.ReactNode }) => <div className="flex items-center gap-2"><Check size={12} className="text-brand-cyan" />{children}</div>;

export function OverviewTab({ report, goTo }: { report: Report; goTo: (tab: "tests" | "failures" | "edges" | "coverage") => void }) {
  const s = report.summary;
  const durations = [...report.results].sort((a, b) => a.id.localeCompare(b.id)).map((r) => r.duration_ms);
  const types = Object.entries(s.failure_types);
  const maxType = Math.max(1, ...types.map(([, n]) => n));
  return (
    <div className="space-y-4">
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Total tests" value={s.total} hint={`${s.endpoints} endpoints`}>
          <Li>{s.by_source.rules ?? 0} from spec rules</Li><Li>{s.by_source.llm ?? 0} generated by AI</Li>
        </StatCard>
        <StatCard label="Pass rate" value={s.pass_rate} unit="%" hint={`${s.passed} of ${s.total} passed`} featured>
          <Li>{s.passed} passed</Li><Li>{s.failed} failed</Li>
        </StatCard>
        <StatCard label="Failures" value={s.failed} hint="by type">
          {types.slice(0, 2).map(([t, n]) => <Li key={t}>{n} × {t}</Li>)}
          {!types.length && <Li>No failures</Li>}
        </StatCard>
        <StatCard label="Latency" value={s.avg_ms} unit="ms avg" hint="per request">
          <Li>p95 {s.p95_ms} ms</Li><Li>max {s.max_ms} ms</Li>
        </StatCard>
      </div>

      <div className="grid gap-4 lg:grid-cols-[1.3fr_1fr_1.3fr]">
        <Card className="p-5"><CardHeader title="Results by category" /><CategoryBars data={s.by_category} /></Card>
        <Card className="p-5">
          <CardHeader title="Pass / fail" />
          <div className="flex flex-col items-center gap-4">
            <Donut value={s.pass_rate} />
            <div className="grid w-full grid-cols-2 gap-2 text-xs">
              {(["critical", "high", "medium", "low"] as const).map((k) => (
                <div key={k} className="flex items-center justify-between"><SeverityBadge severity={k} /><span className="font-medium">{s.severities[k] ?? 0}</span></div>
              ))}
            </div>
          </div>
        </Card>
        <Card className="p-5">
          <CardHeader title="Response time per test" subtitle="in execution order" />
          <Sparkline values={durations} height={150} id="latency" />
          <div className="mt-2 flex justify-between text-[11px] text-muted"><span>{durations.length ? report.results[0]?.id : ""}</span><span>avg {s.avg_ms} ms · max {s.max_ms} ms</span></div>
        </Card>
      </div>

      <div className="grid gap-4 lg:grid-cols-[1.6fr_1fr]">
        <Card className="p-5">
          <CardHeader title="Endpoint health" action={<Button size="sm" variant="ghost" onClick={() => goTo("coverage")}>Coverage view</Button>} />
          <div className="divide-y divide-line/10">
            {report.endpoints.map((e) => (
              <div key={e.operation_id} className="flex items-center gap-3 py-2.5 text-[12.5px]">
                <MethodBadge method={e.method} />
                <span className="min-w-0 flex-1 truncate font-mono text-[11.5px]">{e.path}</span>
                <span className="hidden w-28 truncate text-muted md:block">{e.summary}</span>
                <span className="w-8 text-right text-muted">{e.total}</span>
                <Meter value={e.pass_pct} tone={e.failed ? "fail" : "pass"} className="w-24" />
                <span className={`w-16 text-right text-[11.5px] ${e.failed ? "text-fail" : "text-pass"}`}>{e.failed ? `${e.failed} failing` : "Healthy"}</span>
              </div>
            ))}
          </div>
        </Card>
        <div className="space-y-4">
          <Card className="p-5">
            <CardHeader title="Failure types" action={s.failed ? <Button size="sm" variant="ghost" onClick={() => goTo("failures")}>View all</Button> : undefined} />
            {types.length ? types.map(([t, n]) => (
              <div key={t} className="mb-2.5">
                <div className="mb-1 flex justify-between text-[12px]"><span>{t}</span><span className="text-muted">{n}</span></div>
                <Meter value={(n / maxType) * 100} tone="fail" />
              </div>
            )) : <p className="text-[12.5px] text-muted">Nothing failed in this run.</p>}
          </Card>
          <Card className="p-5 text-[12.5px]">
            <CardHeader title="Run details" />
            <dl className="grid grid-cols-[92px_1fr] gap-y-1.5">
              <dt className="text-dim">Spec</dt><dd className="truncate font-mono text-[11.5px]" title={report.meta.spec_source}>{report.meta.spec_source}</dd>
              <dt className="text-dim">Base URL</dt><dd className="truncate font-mono text-[11.5px]">{report.meta.base_url}</dd>
              <dt className="text-dim">OpenAPI</dt><dd>{report.meta.openapi_version} · API v{report.meta.version}</dd>
              <dt className="text-dim">Engine</dt><dd>{report.meta.llm.enabled ? `${report.meta.llm.provider} · ${report.meta.llm.model}` : "Rule-based (no LLM)"}</dd>
              <dt className="text-dim">Duration</dt><dd>{report.meta.duration_s}s</dd>
              {report.meta.provisioned?.length ? <><dt className="text-dim">Setup</dt><dd>{report.meta.provisioned.join(", ")}</dd></> : null}
            </dl>
          </Card>
        </div>
      </div>

      {report.failures.length > 0 && (
        <div>
          <div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-medium">Top failures</h3><Button size="sm" variant="ghost" onClick={() => goTo("failures")}>All {report.failures.length} failures</Button></div>
          <div className="grid gap-4 lg:grid-cols-2">{report.failures.slice(0, 2).map((f, i) => <FailureCard key={f.id} f={f} featured={i === 0} />)}</div>
        </div>
      )}
    </div>
  );
}
